### ISSUE TITLE
A similar feature exists in Tornado

### ISSUE THREAD

**Issue by ishankhare07** [scripting/betterWebSocketsDemo#1]
I understand you're using node for this, but just to let you know, [tornado](http://www.tornadoweb.org/en/stable/) uses the same concepts/methods. Checkout the [WebSocketHandler](http://www.tornadoweb.org/en/stable/websocket.html?highlight=websocket#tornado.websocket.WebSocketHandler) documentation. Since it follows a similar pattern, i believe you're going in the right direction.

_this is in response to your [post on facebook](https://www.facebook.com/dave.winer.12/posts/396532090554202)_

**Comment by scripting** [comment]
Thanks for the feedback. Much appreciated! ;-)
